services:
  aria2-rpc:
    image: aminelazz/aria2
    container_name: aria2-rpc
    network_mode: bridge
    ports:
      - ${LISTEN_PORT}:6800
    volumes:
      - ${ARIA2_CONFIG_DIR}:/config
      - ${ARIA2_DOWNLOAD_DIR}:/downloads
    # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
    command: aria2c --conf-path=/config/aria2.conf

  aria2-webui:
    image: aminelazz/aria2
    container_name: aria2-webui
    # restart: unless-stopped
    # network_mode: host
    network_mode: bridge
    ports:
      - ${WEBUI_PORT}:80
    depends_on:
      - aria2-rpc
    command: python3.10 -m http.server -d /webui-aria2/docs 80